#!/bin/bash
cd ~/AdditionalDriveA/DeployedProjects/TwoLatentSpacesVAE/paper_experiments/PACS/Jigsaw/
echo "Starting"
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting cartoon sketch --target photo --jig_weight 0.9 --bias_whole_image 0.7 > photo1.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting cartoon sketch --target photo --jig_weight 0.9 --bias_whole_image 0.7 > photo2.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting cartoon sketch --target photo --jig_weight 0.9 --bias_whole_image 0.7 > photo3.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting cartoon sketch --target photo --jig_weight 0.9 --bias_whole_image 0.7 > photo4.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting cartoon sketch --target photo --jig_weight 0.9 --bias_whole_image 0.7 > photo5.txt

python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source photo cartoon sketch --target art_painting --jig_weight 0.9 --bias_whole_image 0.7 > art_painting1.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source photo cartoon sketch --target art_painting --jig_weight 0.9 --bias_whole_image 0.7 > art_painting2.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source photo cartoon sketch --target art_painting --jig_weight 0.9 --bias_whole_image 0.7 > art_painting3.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source photo cartoon sketch --target art_painting --jig_weight 0.9 --bias_whole_image 0.7 > art_painting4.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source photo cartoon sketch --target art_painting --jig_weight 0.9 --bias_whole_image 0.7 > art_painting5.txt

python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo sketch --target cartoon --jig_weight 0.9 --bias_whole_image 0.7 > cartoon1.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo sketch --target cartoon --jig_weight 0.9 --bias_whole_image 0.7 > cartoon2.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo sketch --target cartoon --jig_weight 0.9 --bias_whole_image 0.7 > cartoon3.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo sketch --target cartoon --jig_weight 0.9 --bias_whole_image 0.7 > cartoon4.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo sketch --target cartoon --jig_weight 0.9 --bias_whole_image 0.7 > cartoon5.txt

python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo cartoon --target sketch --jig_weight 0.9 --bias_whole_image 0.7 > sketch1.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo cartoon --target sketch --jig_weight 0.9 --bias_whole_image 0.7 > sketch2.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo cartoon --target sketch --jig_weight 0.9 --bias_whole_image 0.7 > sketch3.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo cartoon --target sketch --jig_weight 0.9 --bias_whole_image 0.7 > sketch4.txt
python train_jigsaw.py --batch_size 128 --n_classes 7 --learning_rate 0.001 --network caffenet --val_size 0.1 --folder_name test --jigsaw_n_classes 30 --train_all True --TTA False --image_size 225 --nesterov True --min_scale 1.0 --max_scale 1.0 --random_horiz_flip 0 --jitter 0 --tile_random_grayscale 0.0 --source art_painting photo cartoon --target sketch --jig_weight 0.9 --bias_whole_image 0.7 > sketch5.txt



echo "Done"
